/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MobileSite: typeof import('./src/components/MobileSite.vue')['default']
    WebSite: typeof import('./src/components/WebSite.vue')['default']
  }
}
